spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: springcloud-simple-config-dev
---
spring:
  profiles: test #测试环境
  application:
    name: springcloud-simple-config-test

#文件格式：UTF-8
